name: "K8mpatible Compatibility Check"
description: "Check Kubernetes tools compatibility with your cluster version"
author: "k8mpatible"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  kubeconfig:
    description: "Path to kubeconfig file. Leave empty to use default location or in-cluster config"
    required: false
    default: ""
  output-file:
    description: "Path to output YAML file for scan results. If not specified, results will only be logged"
    required: false
    default: ""
  fail-on-incompatible:
    description: "Fail the action if any tool is incompatible"
    required: false
    default: "true"

outputs:
  result:
    description: "Compatibility check result"
  compatible:
    description: "Boolean indicating if all tools are compatible"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.kubeconfig }}
    - ${{ inputs.output-file }}
    - ${{ inputs.fail-on-incompatible }}
